# Generated by Django 5.1.1 on 2024-09-04 17:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeVoluntario', models.CharField(max_length=100)),
                ('telefoneVoluntario', models.CharField(max_length=15)),
                ('emailVoluntario', models.EmailField(max_length=100)),
                ('enderecoVoluntario', models.CharField(max_length=100)),
                ('funcaoVoluntario', models.CharField(max_length=100)),
                ('dt_registro_voluntario', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
